# Generated by Django 4.2.5 on 2023-10-23 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_alter_food_description_alter_food_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='type_food',
            field=models.CharField(choices=[('B', 'صبحانه'), ('L', 'ناهار'), ('D', 'نوشیدنی'), ('DI', 'شام')], default='L', max_length=10, verbose_name='نوع غذا'),
        ),
    ]
