# Generated by Django 4.2.5 on 2023-10-23 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0004_alter_food_type_food'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='type_food',
            field=models.CharField(choices=[('breakfast', 'صبحانه'), ('lunch', 'ناهار'), ('drinks', 'نوشیدنی'), ('dinner', 'شام')], default='lunch', max_length=10, verbose_name='نوع غذا'),
        ),
    ]
