# Generated by Django 4.2.5 on 2023-10-27 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام و نام خانوادگی')),
                ('email', models.EmailField(max_length=200, verbose_name='آدرس الکترونیکی')),
                ('phone', models.CharField(max_length=11, verbose_name='شماره موبایل')),
                ('number', models.IntegerField(verbose_name='تعداد نفرات')),
                ('date', models.DateField(verbose_name='تاریخ')),
                ('time', models.TimeField(verbose_name='زمان')),
            ],
        ),
    ]
